name: "custom-test"
on:
  repository_dispatch:
    types: [custom]

permissions:
  contents: read

jobs:
  custom:
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        persist-credentials: false
    - id: build
      run: |
        npm ci
        npm run all
    - uses: ./
      with:
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
        channel: '#actions'
      if: always()
