name: "manual-test"
on: workflow_dispatch

permissions:
  contents: read

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        persist-credentials: false
    - id: build
      run: |
        npm ci
        npm run all
    - uses: ./
      with:
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
        channel: '#actions'
        message: Manual test of {{ env.GITHUB_REF_NAME }} branch...
      if: always()
