name: "workflow-run"
on:
  workflow_run:
    workflows: ["build-test"]
    # branches: [master]
    # types:
    #   - completed
    #   - requested

permissions:
  contents: read

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        persist-credentials: false
    - uses: ./
      with:
        webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
        status: ${{ github.event.workflow_run.conclusion }}
        channel: '#actions'
        config: .github/slack-workflow.yml
      if: always()

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        persist-credentials: false
    - uses: ./
      with:
        status: ${{ github.event.workflow_run.conclusion }}
        channel: '#actions'
        config: .github/slack-workflow.yml
      if: always()
